server:
  port: 8105

spring:
  application:
    name: pricing-service
  cache:
    type: redis
    redis:
      time-to-live: 300000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: ${JWT_ISSUER_URI:http://auth-service:8081}
        jwk-set-uri: ${JWK_SET_URI:http://auth-service:8081/oauth2/jwks}

logging:
  level:
    com.kartezy.pricingservice: INFO
