server:
  port: 8100

spring:
  application:
    name: nlp-service
  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    fetchRegistry: true
    registerWithEureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
