server:
  port: 8080

spring:
  application:
    name: merchant-service
  cloud:
    config:
      uri: http://config-server:8888
    discovery:
      enabled: true
      service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: ${JWT_ISSUER_URI:http://auth-service:8080}
        jwk-set-uri: ${JWK_SET_URI:http://auth-service:8080/oauth2/jwks}