server:
  port: 8111

spring:
  application:
    name: secrets-service

secrets:
  vault:
    address: ${VAULT_ADDR:http://vault:8200}
    token: ${VAULT_TOKEN:}
    kv-path: secret/kartezy

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.kartezy.secretsservice: INFO
