server:
  port: 8086

spring:
  application:
    name: order-service
  cloud:
    config:
      uri: http://config-server:8888
    discovery:
      enabled: true
      service-id: config-server
  # For Consul or other service discovery, but we are using Eureka
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 days in milliseconds

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.type.mapping: event:com.kartezy.shared.events.OrderEvent

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: ${JWT_ISSUER_URI:http://auth-service:8081}
        jwk-set-uri: ${JWK_SET_URI:http://auth-service:8081/oauth2/jwks}