server:
  port: 8097
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kartezy_cms
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
eureka:
  client:
    enabled: false
logging:
  level:
    com.kartezy.cmsservice: DEBUG
