server:
  port: 8098
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kartezy_finance
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
eureka:
  client:
    enabled: false
logging:
  level:
    com.kartezy.financeservice: DEBUG
