spring:
  application:
    name: search-service
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
  elasticsearch:
    host: ${ELASTICSEARCH_HOST:elasticsearch}
    port: ${ELASTICSEARCH_PORT:9200}

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
