server:
  shutdown: graceful
  port: ${PORT:8087}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/kartezy
    username: kartzeuser
    password: kartze-pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      uri: http://config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    instance:
      prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
