server:
  shutdown: graceful
  port: 8102
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: search-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    connection-timeout: 5s
    socket-timeout: 60s
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
  cache:
    type: redis
    redis:
      time-to-live: 300000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
springdoc:
  api-docs:
    path: /search/v3/api-docs
  swagger-ui:
    path: /search/swagger-ui.html
logging:
  level:
    com.kartezy.searchservice: INFO

